### ISSUE TITLE
KeyError: '_name' when training with IIT dataset configuration

### ISSUE THREAD

**Issue by anh0001** [anh0001/affomernet#1]
## Description
When trying to train the model with IIT dataset configuration, encountering a KeyError: '_name' error during model creation. The same code works fine with COCO dataset configuration.

## Environment
- Python environment: affomernet_env
- Configuration file: configs/rtdetr/rtdetr_r50vd_6x_iit.yml

## Error Message
```
Not init distributed mode.
Start training
Load PResNet50 state_dict
Traceback (most recent call last):
  File ".../tools/train.py", line 50, in <module>
    main(args)
  File ".../tools/train.py", line 36, in main
    solver.fit()
  File ".../src/solver/det_solver.py", line 22, in fit
    self.train()
  File ".../src/solver/solver.py", line 45, in train
    self.setup()
  File ".../src/solver/solver.py", line 28, in setup
    self.model = dist.warp_model(cfg.model.to(device), cfg.find_unused_parameters, cfg.sync_bn)
  File ".../src/core/yaml_config.py", line 44, in model
    self._model = create(self.yaml_cfg['model'])
  File ".../src/core/yaml_utils.py", line 123, in create
    cls_kwargs[k] = create(_cfg['_name'])
KeyError: '_name'
```

## Steps to Reproduce
1. Run training with COCO config (works):
```bash
python tools/train.py -c configs/rtdetr/rtdetr_r50vd_6x_coco.yml
```

2. Run training with IIT config (fails):
```bash
python tools/train.py -c configs/rtdetr/rtdetr_r50vd_6x_iit.yml
```

## Configuration Files Structure
The IIT config includes:
```yaml
__include__: [
  '../dataset/iit_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/affomernet_r50vd.yml',
]
output_dir: ./output/rtdetr_r50vd_6x_iit
```

While the working COCO config includes:
```yaml
__include__: [
  '../dataset/coco_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetr_r50vd.yml',
]
output_dir: ./output/rtdetr_r50vd_6x_coco
```

## Additional Context
- No modifications were made to src/core files
- The error occurs during model creation in the yaml_utils.py file
- The main difference is using affomernet_r50vd.yml instead of rtdetr_r50vd.yml

## Questions
1. Are all components in affomernet_r50vd.yml properly registered in the codebase?
2. Are there any missing required fields in the configuration files?
3. Is there a problem with the included YAML file paths?

Would appreciate any help in resolving this issue.

**Comment by anh0001** [comment]
The issue appears to be related to missing model registration. Here's the solution:

Add the following import statement in `src/zoo/rtdetr/__init__.py`:

```python
from .affordance import *
```

### Explanation

The `KeyError: '_name'` error occurs during model creation because the affordance-related components defined in `affomernet_r50vd.yml` aren't properly registered in the model registry. The YAML configuration system tries to create model components by looking up their names in the registry, but fails because the affordance module hasn't been imported.

### Steps to Fix

1. Open `src/zoo/rtdetr/__init__.py`
2. Add the import statement: `from .affordance import *`
3. This will ensure all model components defined in the affordance module are registered when the RTDETR package is imported

### Technical Details

- The error occurs in `yaml_utils.py` during the model creation process because it can't find the component name in the registry
- Adding the import statement ensures that the model registry is populated with all necessary components when the package is initialized
- This matches the pattern used for the COCO model components, which are properly registered through their respective imports

**Comment by anh0001** [comment]
Solved
