### ISSUE TITLE
ValueError in Affordance Branch During Training

### ISSUE THREAD

**Issue by anh0001** [anh0001/affomernet#2]
## Description

While running the training script for the affomernet model with the IIT dataset configuration, a 

ValueError

 occurs in the `affordance_branch` module. The error message indicates that the expected shape of the `decoder_features` tensor does not match the actual shape.

## Error Traceback

```
Not init distributed mode.
Start training
Load PResNet50 state_dict
Initial lr:  [1e-05, 0.0001, 0.0001, 0.0001]
number of params: 43303076
Train one epoch...
Initial x.shape: torch.Size([4, 6, 500, 256])
Initial x.shape: torch.Size([6, 500, 256])
Traceback (most recent call last):
  File "/media/kubotaserver2/afbf2736-1adc-456a-9467-5220deb0ce88/Anhar/codes/affomernet/tools/train.py", line 50, in <module>
    main(args)
  File "/media/kubotaserver2/afbf2736-1adc-456a-9467-5220deb0ce88/Anhar/codes/affomernet/tools/train.py", line 36, in main
    solver.fit()
  File "/media/kubotaserver2/afbf2736-1adc-456a-9467-5220deb0ce88/Anhar/codes/affomernet/tools/../src/solver/det_solver.py", line 52, in fit
    train_stats = train_one_epoch(
                  ^^^^^^^^^^^^^^^^
  File "/media/kubotaserver2/afbf2736-1adc-456a-9467-5220deb0ce88/Anhar/codes/affomernet/tools/../src/solver/det_engine.py", line 61, in train_one_epoch
    outputs = model(samples, targets)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/kubotaserver2/afbf2736-1adc-456a-9467-5220deb0ce88/Anhar/codes/affomernet/affomernet_env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/kubotaserver2/afbf2736-1adc-456a-9467-5220deb0ce88/Anhar/codes/affomernet/tools/../src/zoo/rtdetr/rtdetr.py", line 63, in forward
    aux_output['pred_affordances'] = self.affordance_branch(aux_out['features'])
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/kubotaserver2/afbf2736-1adc-456a-9467-5220deb0ce88/Anhar/codes/affomernet/affomernet_env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/kubotaserver2/afbf2736-1adc-456a-9467-5220deb0ce88/Anhar/codes/affomernet/tools/../src/zoo/rtdetr/affordance.py", line 152, in forward
    batch_size, num_layers, num_queries, hidden_dim = decoder_features.shape
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 4, got 3)
```

## Steps to Reproduce

1. Activate the virtual environment: `source affomernet_env/bin/activate`
2. Run the training script: 
   ```bash
   python tools/train.py -c configs/rtdetr/rtdetr_r50vd_6x_iit.yml
   ```

## Expected Behavior

The training should proceed without errors, and the `affordance_branch` should correctly process the `decoder_features` tensor.

## Actual Behavior

The training script fails with a 

ValueError

 indicating that the `decoder_features` tensor does not have the expected shape.

### 

affordance.py

```python
#...
batch_size, num_layers, num_queries, hidden_dim = decoder_features.shape
#...
```

### 

train.py

```python
#...
solver.fit()
#...
```

### 

det_solver.py

```python
#...
train_stats = train_one_epoch(
#...
```

### 

det_engine.py

```python
#...
outputs = model(samples, targets)
#...
```

### `rtdetr.py`
```python
#...
aux_output['pred_affordances'] = self.affordance_branch(aux_out['features'])
#...
```

## Configuration

- Configuration file: 

rtdetr_r50vd_6x_iit.yml

## Environment

- Python version: 3.11
- PyTorch version: 2.0.1
- Torchvision version: 0.15.2
- ONNX version: 1.14.0
- ONNX Runtime version: 1.15.1

## Additional Context

The issue seems related to the shape of the `decoder_features` tensor passed to the `affordance_branch`. The expected shape is `[batch_size, num_layers, num_queries, hidden_dim]`, but the actual shape is `[6, 500, 256]`.

Please investigate the discrepancy in the tensor shape and provide a fix or guidance on resolving this issue.

This could be that sometimes the tensor has batch size and sometimes not.

**Comment by anh0001** [comment]
I've implemented a solution to handle both 3D and 4D input tensors in the feature decoder. Here's the fixed code:

```python
def forward(self, decoder_features: torch.Tensor) -> dict:
    # Ensure decoder_features always has shape [batch_size, num_layers, num_queries, hidden_dim]
    if decoder_features.dim() == 3:
        # If input is [num_layers, num_queries, hidden_dim], assume batch_size=1
        decoder_features = decoder_features.unsqueeze(0)  # [1, num_layers, num_queries, hidden_dim]
    elif decoder_features.dim() != 4:
        raise ValueError("decoder_features must be a 3D or 4D tensor.")

    batch_size, num_layers, num_queries, hidden_dim = decoder_features.shape
    print(f"Adjusted decoder_features shape: {decoder_features.shape}")
    
    # Proceed with the rest of the forward pass
    features = decoder_features.permute(0, 2, 1, 3).contiguous()
    features = features.view(batch_size * num_queries, -1)
    features = self.feature_combiner(features)
    features = features.view(-1, 1, 7, 7)

    features = F.relu(self.initial_conv(features))
    
    # First upsampling block
    features = F.relu(self.conv1(features))
    features = F.relu(self.deconv1(features))
    
    # Second upsampling block
    features = F.relu(self.conv2(features))
    features = F.relu(self.deconv2(features))
    
    # Third upsampling block
    features = F.relu(self.conv3(features))
    features = F.relu(self.deconv3(features))
    
    # Final prediction
    affordances = self.affordance_predictor(features)
    affordances_mask = affordances.view(
        batch_size, num_queries, self.output_dim, 244, 244
    )
    
    return {'affordances_mask': affordances_mask}
```

The changes:
- Added input shape validation at the start of `forward()`
- For 3D inputs (shape `[num_layers, num_queries, hidden_dim]`), we add a batch dimension using `unsqueeze(0)`
- Added error handling for invalid input shapes
- Added shape logging for debugging purposes

I've tested this with both 3D and 4D inputs, and the model processes them correctly now. The output shape remains consistent in both cases.

Closes #2
