### ISSUE TITLE
CUDA Out of Memory Error during Training

### ISSUE THREAD

**Issue by anh0001** [anh0001/affomernet#3]
## Description

While training the model using the `train.py` script, a CUDA out of memory error occurs. The error traceback indicates that the issue arises during the forward pass of the `affordance_branch` in the affordance.py file.

## Error Traceback

```
Not init distributed mode.
Start training
Load PResNet50 state_dict
Initial lr:  [1e-05, 0.0001, 0.0001, 0.0001]
number of params: 43303076
Train one epoch...
Adjusted decoder_features shape: torch.Size([4, 6, 498, 256])
Adjusted decoder_features shape: torch.Size([1, 6, 498, 256])
Adjusted decoder_features shape: torch.Size([1, 6, 498, 256])
Traceback (most recent call last):
  File "/media/kubotaserver2/afbf2736-1adc-456a-9467-5220deb0ce88/Anhar/codes/affomernet/tools/train.py", line 50, in <module>
    main(args)
  File "/media/kubotaserver2/afbf2736-1adc-456a-9467-5220deb0ce88/Anhar/codes/affomernet/tools/train.py", line 36, in main
    solver.fit()
  File "/media/kubotaserver2/afbf2736-1adc-456a-9467-5220deb0ce88/Anhar/codes/affomernet/tools/../src/solver/det_solver.py", line 52, in fit
    train_stats = train_one_epoch(
                  ^^^^^^^^^^^^^^^^
  File "/media/kubotaserver2/afbf2736-1adc-456a-9467-5220deb0ce88/Anhar/codes/affomernet/tools/../src/solver/det_engine.py", line 61, in train_one_epoch
    outputs = model(samples, targets)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/kubotaserver2/afbf2736-1adc-456a-9467-5220deb0ce88/Anhar/codes/affomernet/affomernet_env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/kubotaserver2/afbf2736-1adc-456a-9467-5220deb0ce88/Anhar/codes/affomernet/tools/../src/zoo/rtdetr/rtdetr.py", line 63, in forward
    aux_output['pred_affordances'] = self.affordance_branch(aux_out['features'])
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/kubotaserver2/afbf2736-1adc-456a-9467-5220deb0ce88/Anhar/codes/affomernet/affomernet_env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/kubotaserver2/afbf2736-1adc-456a-9467-5220deb0ce88/Anhar/codes/affomernet/tools/../src/zoo/rtdetr/affordance.py", line 181, in forward
    features = F.relu(self.deconv3(features))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/kubotaserver2/afbf2736-1adc-456a-9467-5220deb0ce88/Anhar/codes/affomernet/affomernet_env/lib/python3.11/site-packages/torch/nn/functional.py", line 1457, in relu
    result = torch.relu(input)
             ^^^^^^^^^^^^^^^^^
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.54 GiB (GPU 0; 47.44 GiB total capacity; 42.48 GiB already allocated; 1.94 GiB free; 45.16 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

## Steps to Reproduce

1. Run the `train.py` script with the following command:
   ```sh
   python tools/train.py -c configs/rtdetr/rtdetr_r50vd_6x_iit.yml
   ```

## Environment

- GPU: 47.44 GiB total capacity
- PyTorch version: [version]
- CUDA version: [version]
- Python version: 3.11

## Possible Solutions

- Reduce the batch size to decrease memory usage.
- Use gradient accumulation to simulate a larger batch size.
- Set `PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:<value>` to avoid memory fragmentation.

## Additional Context

The error occurs during the forward pass of the `affordance_branch` in the affordance.py file, specifically at the line:
```python
features = F.relu(self.deconv3(features))
```

Any help or suggestions to resolve this issue would be greatly appreciated.

**Comment by anh0001** [comment]
At the current, we set reduced_dim to 8 in the affomernet_r50vd.yml
